### ISSUE TITLE
Refactor the byline component

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/graphics-components#108]
Make the byline and dateline its own thing so that it can be added anywhere on the page – with title, with copy start, or at the end as needed.

**Comment by hobbes7878** [comment]
OK, I've created a `Byline` component and integrated it into both headlines. It's a little different from the styles of both original bylines so that we have something that works with both, but you can much around with it.

Once we're settled with styles, I'll go back over docs that need updating..
