### ISSUE TITLE
Redo heading styles

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/graphics-components#11]
Let's rewrite the SCSS that defines h2 - h6 and make sure new styles respect the new colour and base size CSS variables.

Opportunity to rethink some things: Do we still want center-aligned and underlined ones? Should the sizes follow a different mathematical scheme, e.g., harmonic scale? All the same colour or do we back off to a lighter grey at some point? etc.?

**Comment by pkd2512** [comment]
Working on the typography scheme - https://www.figma.com/file/dmJXhAqC0BFEAc9vMmNwDT/Typography?node-id=0%3A1

This looks interesting https://getbootstrap.com/docs/5.0/getting-started/rfs/

**Comment by hobbes7878** [comment]
cc: #78

**Comment by hobbes7878** [comment]
Closing in favour of #91
