### ISSUE TITLE
Locale datetime shows different timezone strings based on locale and browser

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/graphics-components#115]
At the same time, Chrome shows GMT+5:30 while Safari shows IST. There is an issue with Chrome resolving the user locale. The issue is resolved if the locale is set to `en-IN`, instead of the default.

I propose that we detect the system locale using `window.navigator.language` and if it is an `en-` language, we use that, else default to the project locale. This avoids the issue of showing the dateline in Hindi, is the system locale is `hi-IN` for example.

<img width="515" alt="image" src="https://github.com/reuters-graphics/graphics-components/assets/7580745/3daab1bf-f94a-43b5-ad7c-82ce0cdc8f0b">

<img width="542" alt="image" src="https://github.com/reuters-graphics/graphics-components/assets/7580745/ce8c8355-1b48-49d5-b587-ad772f397a9b">

**Comment by pkd2512** [comment]
This will not work if the user's default language is just `en` or `en-US` instead of the local en version.

**Comment by hobbes7878** [comment]
Closing for now. Can re-open if we decide to revisit.
