### ISSUE TITLE
Graphic legend component

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/graphics-components#117]
Need a smart component that creates custom legends in code, just like the title and dek of a graphic. Instead of Illustrator or DW. This will help harmonise it better with the page.

<img width="1099" alt="image" src="https://github.com/reuters-graphics/graphics-components/assets/7580745/f384b246-a5ef-4cb6-88e0-f55531ef5ee8">

**Comment by hobbes7878** [comment]
Closing for now. If we get to it someday, can re-open.
