### ISSUE TITLE
Canvas?

### ISSUE THREAD

**Issue by travishartman** [reuters-graphics/graphics-components#125]
was reading through docs from beginning and noticed a reference to "Canvas tab" in the "using these docs" section, which i don't seem to be able to find in my browser or it's referring to an outdated version of doc framework?  

also a reference to the canvas tab in the "block" section doc, which if it is outdated, might also need to be amended.  

Also, in the "using these docs" you have example code with byline code in a slot - might need updating - seems out of date with the new array structure for the bylines?

**Comment by hobbes7878** [comment]
Thanks, Travis. Yeah, Storybook made some changes to the UI we picked up with this update looks like we need to account for and probably some outdated stuff in the Guides which we haven't scrubbed yet.

cc: @pkd2512, between us, let's try to weed out any stale references. That Guides section needs some new screenshots for the updated UI, too.

**Comment by hobbes7878** [comment]
Thanks again, @travishartman. Those doc updates will be online momentarily. Let us know if you find any other stale stuff.

**Comment by travishartman** [comment]
Cool!  thanks your responsiveness (see what i did there)  Pretty sure the rest is tip top, nothing else caught my eye but will remain vigilant. On Sep 20, 2023, at 13:59, Jon McClure ***@***.***> wrote:﻿
Thanks again, @travishartman. Those doc updates will be online momentarily. Let us know if you find any other stale stuff.
