### ISSUE TITLE
Freestar is not defined

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/graphics-components#144]
Cf. deployed ads demo: https://www.reuters.com/graphics/HEALTH-CORONAVIRUS/TEST/byvrklraape/

Errors with:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'domain')
    at Fe (pubfig.min.js:1:46248)
    at Object.getApiUrl (pubfig.min.js:1:62025)
    at Object.init (pubfig.min.js:1:62700)
    at new <anonymous> (pubfig.min.js:1:61891)
    at pubfig.min.js:1:61716
    at pubfig.min.js:1:95445
```

Failed line is in this function:

```javascript
function Fe() {
    return window.freestar.fsdata.domain || location.host
}
```

However, `window.freestar` is defined on the window if you check it after first render. 

I'd guess a race condition is unaccounted for in the `AdScripts` implementation.

cc: @GregJunkaTR

**Comment by GregJunkaTR** [comment]
@hobbes7878 Which branch is deployed to the demo page? Can you also post a PR or commits in which you added ads to the code so that I can review and compare with my PR?

**Comment by GregJunkaTR** [comment]
Are you deploying my branch greg-ads to that page?

**Comment by hobbes7878** [comment]
Yes, this branch is what we're testing. I've pushed my code directly after you. If you push new code, it'll create a new alpha version of this library, which I can then update in the published project.

**Comment by GregJunkaTR** [comment]
cc @OffTop1

**Comment by OffTop1** [comment]
@hobbes7878 @GregJunkaTR I haven't observed the issue described here. 
From what I observed, the reason for ads not being displayed is that the callback function(loadBootstrap) attached to the onLoad event of the static.bootstrap.js script element is not fired on a test page. And the only reason I can think of is that the load event is happening before the loadBootstrap is added as a callback to the script element.

Also, as I said on the other chat, the storybook story doesn't have this issue.

**Comment by OffTop1** [comment]
Moreover, before that I observed another issue where freestar variable was declared like the below in loadBootstrap:
const freestar = window.freestar || {}
If window doesn't have feeestar global object already by the time loadBootstrap is called, then freestar will reference to newly created empty object and the code below that line populate that empty object and then freestar script won't pickup the configurations we made in loadBootstrap function. That one just will be scoped to the block only and global freestar object won't affected by those changes.

**Comment by GregJunkaTR** [comment]
Thanks @OffTop1  Can you please list the events that according to your understanding should be happening when the page is loaded? Not what's implemented but what would be the order of events in the ideal scenario, including bootstrap and freestar initialization

**Comment by OffTop1** [comment]
Yes, the flow should be following based on my understanding:

1. Load bootstrap script
2. When the above is loaded do freestar object setup and register initCallback of bootstrap
3. When bootstrap work finishes, load pubfig.min.js
4. Then it will laod other ad related scripts and turn on ads on the site
