### ISSUE TITLE
Use image processing by importing images directly in code

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/graphics-components#22]
So we're starting to develop a handy convention for ai graphics that looks like importing the component, adding to an object...

```svelte
<script>
  import MyMap from './ai2svelte/my-ai-map.svelte
  
  const aiCharts = {
    // ...
    MyMap,
  };
</script>
```
... and then using that object key in a Google doc to tie the component to its other prop options:

```yaml
Type: ai-graphic
ID: MyMap
# other props...
```

```svelte
{:else if block.Type === 'ai-graphic'}
  <GraphicBlock>
    <svelte:component this={aiCharts[block.ID]} />
  </GraphicBlock>
```

Now, it occurs to me we could do something similar for images which has a **big** benefit because we could then use some existing Vite plugins to optimise our images on build, e.g. [vite-imagetools](https://github.com/JonasKruckenberg/imagetools/blob/main/docs/guide/getting-started.md).

So it would look like:

```svelte
<script>
  // Resize to 1200px width, convert to webp and optimise at 80% quality, for example...
  import MyImage from './images/my-image.jpg?w=1200&webp&quality=80';
  
  const images = {
    // ...
    MyImage,
  };
</script>
```

Tied into a Google doc the same way:

```yaml
Type: feature-image
ID: MyImage
Width: wider
# etc...
```

... and then we'd use it like:

```svelte
{:else if block.Type === 'feature-image'}
  <FeaturePhoto
    width={block.Width}
    src={images[block.ID]}
  />
```

We could even think about adapting images for srcsets, if the component works as expected, and I don't _think_ I see any reason we couldn't adapt the same import strategy into ai2svelte if we wanted to, for example, convert the pngs to webps... 

Tagging a few folks in case there are limits here I haven't thought of...
@pkd2512 @fcage @MinamiFunakoshiTR

**Comment by hobbes7878** [comment]
For one thing, looks like vite-imagetools can't detect imports in CSS, so where we're using `url(...)` I think we'd need to do a little more work to pass the URL through a CSS variable like:

```svelte
<script>
  import MyImage from './images/my-image.jpg?w=1200&webp&quality=80';
</script>

<div style="--bg-img: url('{MyImage}');"></div>

<style>
div {
  background-image: var(--bg-img);
}
</style>
```

**Comment by pkd2512** [comment]
It is interesting in terms of ease of use. However, I am curious about the limitations of vite image tools, because there are some definite issues I found when using the image-optimise feature in the graphicskit

**Comment by hobbes7878** [comment]
Quick test with this...

```js
import Shark from './shark.jpg?width=800&quality=80';
```

... cut the 213kb original down to 27kb over the wire. It also worked with `FeaturePhoto` as currently written, since the imported module is a URL source string. 

Two annoying discoveries, tho:

Our graphics server doesn't currently support a `.webp` file extension and will block the file. Fine to stick with jpg/png for now (tho I selfishly wanted that lighthouse box ticked for modern image formats...). Also something I might be able to get Dipak to resolve...

Second, while the image path is a full url in the prerendered HTML, it gets reset to a relative link (also in dev) once the app hydrates -- unsure why -- which needs to be prefixed with SvelteKit's `assets` path module to work. Basically means we have to do something like this:

```svelte
<script>
  import { assets } from '$app/paths';
  import urlJoin from 'proper-url-join';
  import sharkImg from './shark.jpg?width=800&quality=80';
</script>

<FeaturePhoto src="{/^http/.test(sharkImg) ? sharkImg : urlJoin(assets, sharkImg)}" />
```

A bit annoying, but for the upside of shipping dramatically smaller images, I'd write a util for that. May work out-of-the-box for SREPs, since SvelteKit isn't involved.

@pkd2512 I'll hold to hear about the trade-offs you see and what alternatives you suggest. But compared to how we're currently shipping images in many cases _without_ minimising them at all, this pattern seems pretty accessible and maybe it's already worth shipping the kit with imagetools plugin installed and documenting it as an option, anyway.
