### ISSUE TITLE
More Photopack layout options

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/graphics-components#28]
Like this more column-wise orientation in the NYT:

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/2772078/189309963-09e451f2-6aa4-49fb-9fc2-92bcdd7bd8e0.png">

**Comment by pkd2512** [comment]
Yea, this is a good idea. However, I would like to propose this a a fresh component that helps create a `masonry-grid` like this. It can have photos and videos as well - like we did in Sam's weapons piece. 

- Use a simple matrix to define the layout (like the old photopack component you had made)
- Change the matrix at whatever breakpoints as needed
- The grid items can be simple slots wherein you can pass any of our basic components - ai2svelte, img, video etc.

**Comment by hobbes7878** [comment]
Closing for now. Can re-open to revisit when we have a project needs it.
