### ISSUE TITLE
Scroller Props

### ISSUE THREAD

**Issue by travishartman** [reuters-graphics/graphics-components#34]
Seems like only a small portion of the props listed in the scroller documentation is available for using through the googledoc?  

I've looked in the docProps.js and it only lists
       ID,
       Width,
        ForegroundPosition,
        StackBackground 
       EmbeddedLayout,
       and the steps- 
            
           whereas in the docs it lists many more i.e. top/bottom/threshold/ etc for better scroller customization.  Would be a great addition to incorporate these other props listed in the docs into the standard package as It does seem to advertise such.

**Comment by hobbes7878** [comment]
Closing in favour of #35
