### ISSUE TITLE
Body font swap not working

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/graphics-components#36]
Currently, the body font uses the variable for serif text, so it cannot be changed easily to a sans-serif theme using the CSS variables.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/7580745/198276445-e68a89ad-2038-4d0c-a026-35ebf84021a1.png">

Ideally, the body font variable.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/7580745/198276651-8451abcc-693d-4cae-9947-3d7a27bf2894.png">

**Comment by pkd2512** [comment]
Same issue with hed styles

<img width="389" alt="image" src="https://user-images.githubusercontent.com/7580745/198513684-346ca2e6-6431-4740-98e9-55698b02c792.png">

**Comment by hobbes7878** [comment]
This is handled in another way now
