### ISSUE TITLE
Small typo on Video component docs

### ISSUE THREAD

**Issue by AditiBhandariTR** [reuters-graphics/graphics-components#43]
The Video component uses the `width` attribute to determine the size, but the docs currently say `size={'wide'}`

We need to change the `size` to `width`

**Comment by juruwolfe** [comment]
Came here to leave this issue! I've never actually edited the docs before, so would be happy to do it myself as a way to learn how we update our comp docs if @deaxmachina doesn't mind showing me the way

**Comment by MinamiFunakoshiTR** [comment]
Oh oops didn't realise we already had an issue open. I went ahead and made a PR with these typo fixes (I found more on the FeaturePhoto and css sections).

https://github.com/reuters-graphics/graphics-components/pull/49

Closing this one in favour of https://github.com/reuters-graphics/graphics-components/issues/48
