### ISSUE TITLE
lost in translation

### ISSUE THREAD

**Issue by travishartman** [reuters-graphics/graphics-components#58]
In attempting to present the Peruvian Blockades story in Spanish, we ran into a few issues with the docs / rig and was hoping to instigate the production for a clearer set of instructions on how to best achieve a more streamlined way to implement foreign language presentation for our stories.  

here is the page for reference: https://github.com/tr/graphics_2023-peru-blockade.git

Minami shifted the structure of the code to implement the translation (thanks!), but mentioned (i don't want to speak for Minami, but as best i recall) there may be ways to optimize the process and update documents.  

Happy to discuss further, but wanted to submit a ticket to kick off whatever the best way to improve the rig is.

**Comment by hobbes7878** [comment]
Why don't we have a short meet up sometime soon and y'all can tell me how translation came together for that one. Pain points, things unclear in the docs, etc.

Hopefully can farm that into discrete tickets for improvements.

Whatchu think @travishartman @MinamiFunakoshiTR?

**Comment by travishartman** [comment]
sounds like a fine plan to me - i'm very available during the normal times - we might want to include @juruwolfe as she's got some ideas around this as well - shall we aim for this week or next?

**Comment by juruwolfe** [comment]
Yes please!

**Comment by MinamiFunakoshiTR** [comment]
Sounds good to me too
