### ISSUE TITLE
Graphic block doesn't allow description without title

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/graphics-components#68]
https://github.com/reuters-graphics/graphics-components/blob/d2eb891fccc2125c76288f28debae58fdc00c040/src/components/GraphicBlock/GraphicBlock.svelte#L91

If there is no title, the graphic description doesn't show up.
A typical use case can be when you want a small chart description in line with the section without a chart title as such.

**Comment by hobbes7878** [comment]
I _think_ this was intentional. As I recall the thinking was: if you aren't creating a pack of title/dek, you would use the BodyText component to write through the chart and style that as needs be. We can rethink that if we want. As a hard-coded rule, I agree it's a bit implicit...
