### ISSUE TITLE
Allow custom CSS injection on datawrapper charts

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/graphics-components#77]
Sometimes we may need custom styling on DW charts, like hiding axis ticks or changing the colour of labels and so on. It will be useful to be able to add custom CSS when the component loads.

[example](https://redstapler.co/how-to-apply-css-to-iframe/)

**Comment by hobbes7878** [comment]
I think injecting CSS into an iframe is a bit too hacky to be a supported feature. We probably, also, shouldn't use datawrapper in those cases where we are doing anything outside the box.
