### ISSUE TITLE
Scrolly preload doesn't work with ArchieML integration

### ISSUE THREAD

**Issue by VijdanKawoosaTR** [reuters-graphics/graphics-components#81]
There's an option for us to set preload count for the srolly element. But when we set that in ArchieML, it is not effective on the project.

For a recent project, @pkd2512 helped me set it manually in the code:

{:else if block.Type === 'ai-scroller'}
      {@const newBlock = { ...block, Preload: 0 }}
      <Scroller
        {...scrollerProps(newBlock, aiCharts, assets || '/')}
        embedded="{embedded}"
      />

Is this something we can fix so that it can work directly from ArchieML?

**Comment by pkd2512** [comment]
`"Preload": "0"` doesn't work. `Preload: 0` works
@hobbes7878 Basically the ArchieML parse treats numbers as strings, so it's a problem for all situations when we need `int` instead of `strings`.

So, the fix can be in the `scrollerProps` or our ArchieML parser in general.
